name: Update README

on:
  schedule:
    - cron: '* * * * *' # Run every day at midnight (UTC)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "Abhinand-s"
          git config --global user.email "abhinands488@gmail.com"

      - name: Install dependencies
        run: npm install node-fetch

      - name: Fetch data and update README
        run: node update_readme.js
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}

      - name: Commit and Push Changes
        run: |
          git add README.md
          git commit -m "Update README with recent issue data [$(date +'%Y-%m-%d %H:%M:%S')]"
          git push -f origin main

