name: Pacman Game

on:
  issues:
    types: [opened]

jobs:
  move-pacman:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Process issue and move Pacman
      run: |
        ISSUE_BODY=$(jq -r '.issue.body' "$GITHUB_EVENT_PATH")

        # Extract coordinates from the issue body
        X_COORD=$(echo "$ISSUE_BODY" | grep -oP 'X:\s*\K\d+')
        Y_COORD=$(echo "$ISSUE_BODY" | grep -oP 'Y:\s*\K\d+')

        # Read the current game board
        GAME_BOARD=$(sed -n '/## Game Board/,/^$/p' README.md)

        # Get current Pacman position
        CURRENT_POSITION=$(echo "$GAME_BOARD" | grep -n 'P' | awk -F':' '{print $1}')

        # Get the target position line
        TARGET_LINE=$(echo "$GAME_BOARD" | sed -n "${Y_COORD}p")

        # Extract the specific column in the target line
        TARGET_VALUE=$(echo "$TARGET_LINE" | awk -v col="$X_COORD" -F'|' '{print $col}' | tr -d '[:space:]')

        # Check if the target position is not a wall
        if [ "$TARGET_VALUE" != "W" ]; then
          # Replace current Pacman position with a dot
          NEW_GAME_BOARD=$(echo "$GAME_BOARD" | sed "${CURRENT_POSITION}s/P/./")

          # Replace the target position with Pacman
          NEW_GAME_BOARD=$(echo "$NEW_GAME_BOARD" | sed "${Y_COORD}s/| $X_COORD |/| P |/")

          # Update the README file
          sed -i "/## Game Board/,/^$/c\\$NEW_GAME_BOARD" README.md

          # Commit and push the changes
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Move Pacman to ($X_COORD, $Y_COORD)"
          git push
        else
          echo "Invalid move. The target position is a wall."
        fi
