name: Update Pacman

on:
  issues:
    types: [opened]

jobs:
  update-pacman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Run JavaScript script
        run: |
          npm install
          node update_readme.js ${{ github.event.issue.title }}
