name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "Abhinand-s"
          git config --global user.email "abhinands488@gmail.com"

      - name: Fetch data and update README
        run: |
          npm install node-fetch
          node index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push Changes
        run: |
          git add README.md
          git commit -m "Update README with recent issue data"
          git push
